### ISSUE TITLE
problem with poly=None

### ISSUE THREAD

**Issue by slhowardESR** [ICESat2-SlideRule/sliderule-python#105]
Hi, I am re-testing the parallel scripts Tyler wrote to process the large set of granules we need for our work.

We will process complete region 10 and region 12 granules.

I have the following a couple of lines  in it: 

            parm = dict(region=reg, rgt=rgt, cycle=cycle, poly=None)
            resources = icesat2.__query_resources(parm, version=args.release)

this worked previously

but now it looks like there is an error with  setting poly to None:
![poly_none](https://user-images.githubusercontent.com/5480396/178338008-934a8be1-670a-4af4-b411-0bd2f67875ed.PNG)

Maybe I just need to do something differently (maybe not include the poly parameter in the parm set now?), but wanted to  just check on the change.    I can send you the full script if that is helpful .  Thanks!

**Comment by jpswinski** [comment]
@slhowardESR Sorry that this issue was added to the code.  It looks like I introduced this behavior when I was adding support for clustering large sets of polygons.

I have reproduced the problem locally, and I have a fix that I will release right away.  But before I do, can you send me a sample set of the following inputs: reg, rgt, cycle, args.release?  I want to test it out with the parameters you are using and send you back the list of resources I am seeing returned in order to fully verify that it works.

**Comment by slhowardESR** [comment]
hi JP, thanks for looking at this and working on a fix.

here is what I have for a set of these
reg  = ['10', '12']
rgt=['0235', '0236', '0237', '0238', '0239', '0240', '0241', '0242', '0243', '0244']
cycle =  ??
args.release= 005

let me know if you need more info .

Thanks!

**Comment by jpswinski** [comment]
@slhowardESR the updated Python client v1.4.4 has been released and l believe solves this issue.  Please update your client and let me know if it now works.  Thanks!

**Comment by slhowardESR** [comment]
I updated and it seems to be working just fine now.  Thanks!!
