### ISSUE TITLE
Should `development` be the default branch on GitHub?

### ISSUE THREAD

**Issue by jhkennedy** [ICESat2-SlideRule/sliderule-python#121]
For openjournals/joss-reviews#498, I noticed if you do a fresh clone of `sliderule-python` like:
```shell
git clone git@github.com:ICESat2-SlideRule/sliderule-python.git
cd sliderule-python
```
You'll check out the `main` branch on commit c8cec49, which is tagged `v1.5.6`. However, the latest release for sliderule-python is `v1.5.8`, which is tagged on the `development` branch:
```shell
git log --graph --decorate --pretty=oneline --abbrev-commit --author-date-order --all
```
![image](https://user-images.githubusercontent.com/7882693/209867637-9f98947c-ab15-4faa-bc4c-2da3373a0da5.png)

Likewise, when forking the repo, you'll be prompted to fork only the `main` (default) branch of the repo, so community development likely will be based off of an old version and make syncing the changes with `development` difficult.
![image](https://user-images.githubusercontent.com/7882693/209899509-f52af794-90c9-4cf4-96a4-e2f8b0bec9f2.png)

**Comment by jpswinski** [comment]
You've hit upon an issue we are still trying to figure out.  

The issue is coordinating the deployment of a new version of sliderule between the client and the server.   When we tag and generate a release, the ICESat2-SlideRule/sliderule repo is used to build new docker images for the backend servers.  The public cluster is then redeployed with the latest images.

But all of that takes some time (a few hours), which means that if the just-tagged release of sliderule-python is used during that time, there is the possibility for scripts (and tests) to fail because the servers are still running the old version of the code.

In general, we don't have so many people pulling `main` on sliderule-python all the time to make this a real problem; but we have automated self-tests that run on every push to `main`, which do fail almost every time a release occurs for the reason described above.

So I am trying to work out a process where the automated self-tests are always kept in the green, and also any users that do pull from `main` as their method of updating their client are kept stable.

The solution I've tried out recently is what you discovered - I am tagging the `development` branch and then letting the `main` branch be behind.  In this case, there was a little bit of a hiccup right before the holidays on the merge to `main`, so I put it off until I came back.

I'm still working out the kinks in the process, and I'm not sure it is what I want to do.  I'd value any thoughts you have, or if you have any recommendations on how you've solved similar issues.

**Comment by jhkennedy** [comment]
Interesting! the long deployment window does make this challenging. We deploy in minutes, so we don't usually worry about it, and our API is relatively stable, so we don't sync versions across HyP3 and the HyP3 SDK. We haven't really figured out how to handle braking API changes well, though.

The strategy I'd try^ is:
* In SlideRule
  * merge to main and trigger the deployment from that (automatically if possible, but manually if not)
  * once deployed and verified, create the tag (as the last step in the deployment process)
* When a new sliderule tag is created, trigger a release of sliderule-python, etc.

It'd probably make sense to merge everything to `main`, when you're ready to deploy, but not tag until it's actually deployed and trigger the release on the tag. So, using `main` as a deployment staging area. 

That's all envisioning using `development` as the default branch and might necessitate the automated self-tests to be triggered on tags, not pushes to `main`. 

But I'm not the above is necessarily any better than what you have worked out. :thinking: 

---

^ My experience with all things CI/CD is that it's always living thing that gets tried and then tweaked over time.

**Comment by jpswinski** [comment]
@jhkennedy You bring up some good points.  

Thinking through your suggestions and what we are trying to do, making the `development` branch the default branch may be a good fit for our current approach.  That way `main` always matches the deployment of the public service.  It's not so much that the APIs change, but that new releases usually include a new feature requested by the UW team - a feature that has an automated pytest that goes along with it, which then fails if the deployed server doesn't have that feature implemented.  And we still need to tag before deploying because clients request version info to attach to their results.

I'll bring this up with the rest of the team and see what their thoughts are.

**Comment by jpswinski** [comment]
@jhkennedy We've decided to take your suggestion and make the `development` branch the default branch.  Thank you for your input here.

**Comment by jpswinski** [comment]
We unexpectedly had issues with some new users who cloned the repo and wanted to use the client against the public cluster.  We failed to provide documentation that they needed to switch to the `main` branch before using the public cluster.  This caused a lot of confusion.  After further internal discussions, we are reverting the default branch back to `main`.  We believe it is easier for developers/contributors to understand branching considerations vs. new data users.
