### ISSUE TITLE
Add binder links to launch examples

### ISSUE THREAD

**Issue by dshean** [ICESat2-SlideRule/sliderule-python#14]
Was reviewing the doc: https://sliderule-python.readthedocs.io/en/latest/getting_started/Examples.html and realized we should set up mybinder for this repo and add links to README and doc, so people can easily run these examples on ephemeral instance without installing locally.

@scottyhq or @tsutterley is this something you can set up pretty easily?   Can we constrain to same AWS data center as current storage and SlideRule cluster?

**Comment by tsutterley** [comment]
@dshean since we already set up the requirements and environment files, it can be literally just adding badges to the README. We can add a postBuild file for some jupyter add-ons (like widgets).  As far as I know, mybinder doesn't want projects to use their platform as "official" front ends so if we start getting a lot of people using sliderule then we might need to rethink things.

```markdown
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/ICESat2-SlideRule/sliderule-python/main)
```

As far as constraining to AWS, I think (but could easily be wrong) that mybinder runs on GCP.  We could think about creating and hosting a binderhub/pangeo-binder on AWS. @scottyhq what do you think?  Should we talk to @salvis2?

**Comment by scottyhq** [comment]
> As far as I know, mybinder doesn't want projects to use their platform as "official" front ends so if we start getting a lot of people using sliderule then we might need to rethink things. 

> As far as constraining to AWS, I think (but could easily be wrong) that mybinder runs on GCP

https://mybinder.org resolves to server different cloud-providers including ovh in europe, so if you want to ensure you're within a U.S. datacenter, you can use https://gke.mybinder.org for the badge link. similarly you can use https://aws-uswest2-binder.pangeo.io but i don't know how long that will be available. really all of these services are for the benefit of open-source development, but as volunteer projects could be dropped at any time. So totally in agreement with @tsutterley if you want something official you need to support your own infrastructure or use some other system. 

but let's definitely add some badges since it is great for demos and getting things tested!
