### ISSUE TITLE
Issues with Multipolygons and complex shapes

### ISSUE THREAD

**Issue by bessoh2** [ICESat2-SlideRule/sliderule-python#24]
Provided is a complex polygon (>5000 vertices) that is reading as a multipolygon.

[UpperTuolRiverBasinOutline.geojson.zip](https://github.com/ICESat2-SlideRule/sliderule-python/files/6455037/UpperTuolRiverBasinOutline.geojson.zip)

**Comment by jpswinski** [comment]
* Increased the maximum number of points in a polygon supported by the server to 16384
* Added buffering step prior to simplify inside the `toregion` function
* Updated the warning log message when a polygon is too large (says "unsupported" instead of "invalid"; provides what maximum number of points is)
* CMR does not accept the provided geojson file, even when using the shapefile API and the 'simplify-shapefile' parameter set to true.  It could be that the request is too large or that the internal structure of the file is not supported.  Continuing to work on this.
```python
>>> search_url = "https://cmr.earthdata.nasa.gov/search/granules"
>>> parameters = {
    "scroll": "true",
    "page_size": 100,
}
>>> search_parameters = {
    'short_name': 'ATL03',
    'version': '003', 
    'provider': 'NSIDC_ECS',
    'simplify-shapefile': 'true',
}
>>> files = {"shapefile": (geojson, open(geojson, "r"), "application/geo+json")}
>>> response = requests.post(f"{search_url}.json", params=parameters, data=search_parameters, files=files)
HTTPError: 400 Client Error: Bad Request for url: https://cmr.earthdata.nasa.gov/search/granules.json?scroll=true&page_size=100
```

**Comment by dshean** [comment]
One note - JP, not sure if this is part of issue you described earlier, but buffering uses the units of the coordinate system for the input vector data.  Could have input in geographic coordinates (WGS84, degrees lat/lon) or projected coordinates (UTM, meters).  So using buffering of 1 could be 111 km or 1 m depending on input.  geojson, by definion, only uses EPSG:4326

**Comment by dshean** [comment]
I think the `simplify-shapefile` option is on CMR side - tough to see the legacy ESRI shapefile still equated with generic vector/polygon data.  But it looks like they can accept geojson. I wonder if converting to a shapefile and retrying the query might work?

**Comment by jpswinski** [comment]
I was not able to get the shapefile to work with cmr.  I think this issue is with me.  I am setting the type=application/shapefile+zip, but the error that comes back is not the normal "Bad Request".  That being said, even when I am able to get get past the URL size limit, cmr is then responding with: "Request Entity Too Large"

So what I've done is added code to the icesat2.py cmr api that will recursively attempt to simplifying the polygon until the cmr system accepts the request. The simplified polygon is only supplied to cmr for the purposes of getting the granules, and then the full resolution polygon is sent to sliderule to do the subsetting.  So this might be the best case for both. (386c1b8)

**Comment by dshean** [comment]
I think this issue is with CMR API, not you :)  
I like your solution.  Hopefully not too much overhead to slog through extra granules.

**Comment by jpswinski** [comment]
The last step in resolving this issue is now complete.  The server-side subsetting code has been optimized (and in the process, a race condition in the code was discovered and fixed).  The 5484 point polygon for UpperToul takes a considerable amount of CPU to process, and further optimizations may be needed, but the server-side code now at least handles it moderately well.  

Here are the commits:
ICESat2-SlideRule/sliderule@9b8ef1b202c68cdf822f2eb1571c5b4281e81d0d
ICESat2-SlideRule/sliderule-icesat2@1def8156d7760ea23afd00eedcdf701238196ff1
ICESat2-SlideRule/sliderule-icesat2@8ada3a0394124827dab5696847035c03dcc69190

@bessoh2 I've loaded the corresponding granules to our S3 bucket, and will deploy the updated code to production either tomorrow or Monday.  As soon as it is deployed, I will let you know, and you should be able to rerun your tests successfully.

**Comment by bessoh2** [comment]
Thank you @jpswinski ! Sounds like great progress, and I look forward to testing again once the updates are deployed.

**Comment by jpswinski** [comment]
@bessoh2 we just deployed updated servers with the code to handle large polygons.  Please take a look and let me know if you run into any issues (feel free to get my contact info from @dshean if you want to reach out directly).

Couple things to note:
1. You will need to do a `git pull` in this repository, followed by a `python setup.py install` to get some updates needed in the client to handle the large polygons.
2. There is a performance hit when using large polygons.  For example, I did some quick tests and it takes about 85 seconds to calculate elevations for the 5000+ point polygon, and for the same region, it takes about 25 seconds when the polygon is simplified to 32 points.
3. I used a tolerance of 0.01 to simplify the polygon to 32 points.  I've attached plots below for the region simplified using no tolerance, 0.001, 0.005, and 0.01 respectively.
![UpperTuol_000_5484](https://user-images.githubusercontent.com/54070345/118716042-62a6cf80-b7f2-11eb-80e4-ceddb39d6e34.png)
![UpperTuol_001_350](https://user-images.githubusercontent.com/54070345/118716044-62a6cf80-b7f2-11eb-8a22-ba602e91b16d.png)
![UpperTuol_005_73](https://user-images.githubusercontent.com/54070345/118716045-62a6cf80-b7f2-11eb-9eb1-e26533aff80d.png)
![UpperTuol_010_32](https://user-images.githubusercontent.com/54070345/118716047-633f6600-b7f2-11eb-8c0a-e6801568cf12.png)

**Comment by dshean** [comment]
Would be good to test tolerance settings for polygons near the equator, at mid latitudes and near poles, as length of 0.01 degree will vary considerably.

**Comment by dshean** [comment]
Linking to related icepyx discussion on CMR polygon (and shapefile) complexity: https://github.com/icesat2py/icepyx/issues/159

**Comment by dshean** [comment]
Ah, accidentally closed.

**Comment by jpswinski** [comment]
@dshean if I buffer out the polygon first by the same tolerance I use to simplify, does that guarantee that the resulting polygon contains a superset of the points of the original one?

**Comment by bludka** [comment]
Hi all, I am new to icepyx (and python) but I think I ran into a related issue. I'm using IS2 data to look at the bathymetry of a coral reef around the tropical island of Yap. I drew this outline in gray around the reef as the "spatial_extent" to input into icepyx
<img width="401" alt="Screen Shot 2021-06-16 at 11 13 26 AM" src="https://user-images.githubusercontent.com/28815558/122271427-3edbb580-ce94-11eb-8ebd-b4b651e2b303.png">
It looks good when I do "region.visualize_spatial_extent()"
<img width="443" alt="Screen Shot 2021-06-16 at 11 20 15 AM" src="https://user-images.githubusercontent.com/28815558/122272035-f4a70400-ce94-11eb-8a0e-0523deeadf1a.png">
But when I print the CMRparams, "print(region.CMRparams)" the polygon is just a triangle (apologies for the bad aspect ratio, but hopefully you know what I mean):
<img width="464" alt="Screen Shot 2021-06-16 at 11 23 22 AM" src="https://user-images.githubusercontent.com/28815558/122272325-48195200-ce95-11eb-82a1-123879d0df20.png">
By comparing the icepyx downloads to what is available using OpenAltimetry, I can see icepyx grabs the data from track 1123 but totally misses track 109. I got around this issue by inputing a larger box as a bounding box into icepyx for now, but just thought I'd document here in case it is related.
Thanks for creating this awesome tool!

**Comment by jpswinski** [comment]
@bludka - thanks for the information.  Can you send me the geojson or shapefile you are using for the polygon?  I want to see how we handle it in SlideRule.  Also - I wasn't sure from your post if you realized that icepyx and sliderule are separate projects.

**Comment by bludka** [comment]
Ah, apologies, I didn't realize I posted to sliderule. I saw these [issues](https://github.com/icesat2py/icepyx/issues/159) were linked and thought they were both within icepyx. Probably not relevant here then? (Also still very likely this is user error to begin with as I am a newbie.) I wasn't able to attach the geojson. I can send via email if you like, but I also read it in myself in the code so again probably not relevant?:

-----
reef_gjson = read_geojson(reef_gjson_fp)
coords = reef_gjson.features[0].geometry.coordinates[0]
spatial_extent = [] 
for i in range(len(coords)):
    coord = coords[i]
    lon = coord[0]
    lat = coord[1]
    spatial_extent.append((lon,lat))
print(spatial_extent)

# create query for specified spatial extent and date range
region = ipx.Query('ATL03', spatial_extent, date_range) # grab data within complex polygon matching reef outline
region.visualize_spatial_extent()
print(region.CMRparams)
------
This is what "print(spatial_extent)" outputs:
[(138.133163, 9.631553), (138.131447, 9.625461), (138.1287, 9.617337), (138.123894, 9.611582), (138.119431, 9.605489), (138.114967, 9.599057), (138.109131, 9.591271), (138.102608, 9.585855), (138.098831, 9.577392), (138.093681, 9.572652), (138.093338, 9.563511), (138.087158, 9.56148), (138.082008, 9.555386), (138.077545, 9.54726), (138.073425, 9.540828), (138.069649, 9.534395), (138.065872, 9.527284), (138.061409, 9.519158), (138.057289, 9.513402), (138.053169, 9.506969), (138.049393, 9.501212), (138.046646, 9.495794), (138.044243, 9.489699), (138.041153, 9.483604), (138.041496, 9.47717), (138.042526, 9.471074), (138.04081, 9.465656), (138.038406, 9.460915), (138.03772, 9.454819), (138.036346, 9.4494), (138.035316, 9.443304), (138.03154, 9.435854), (138.03051, 9.429419), (138.029823, 9.422645), (138.032913, 9.417565), (138.043213, 9.420274), (138.050079, 9.422984), (138.054886, 9.427725), (138.059349, 9.432806), (138.064156, 9.435854), (138.071365, 9.438902), (138.078575, 9.44195), (138.089218, 9.448046), (138.094368, 9.453803), (138.101578, 9.458206), (138.106384, 9.462947), (138.111877, 9.466672), (138.117714, 9.471074), (138.12149, 9.476154), (138.129387, 9.480895), (138.13385, 9.48462), (138.13694, 9.489361), (138.142776, 9.490715), (138.147926, 9.492408), (138.154449, 9.493424), (138.161316, 9.495117), (138.168526, 9.498842), (138.174362, 9.502567), (138.178825, 9.507307), (138.182945, 9.510355), (138.185692, 9.515434), (138.189125, 9.518481), (138.194618, 9.52119), (138.200111, 9.523899), (138.204918, 9.527623), (138.205948, 9.532702), (138.206291, 9.538458), (138.209038, 9.543198), (138.212128, 9.548615), (138.214531, 9.553693), (138.215904, 9.55911), (138.214531, 9.564866), (138.210068, 9.567574), (138.208008, 9.570959), (138.208694, 9.577392), (138.206635, 9.58247), (138.202515, 9.588902), (138.198738, 9.594318), (138.194618, 9.599396), (138.190498, 9.604474), (138.188095, 9.60989), (138.186378, 9.615644), (138.184319, 9.62106), (138.180542, 9.623768), (138.177109, 9.626815), (138.177795, 9.631892), (138.177452, 9.637984), (138.176422, 9.6434), (138.174362, 9.649154), (138.171959, 9.654569), (138.168869, 9.659646), (138.163376, 9.662354), (138.156166, 9.659985), (138.15136, 9.655923), (138.146553, 9.650508), (138.14209, 9.645431), (138.137283, 9.641031), (138.133163, 9.631553)]
-----
This is what "print(region.CMRparams)" outputs:
{'short_name': 'ATL03', 'version': '004', 'temporal': '2019-01-01T00:00:00Z,2021-04-30T23:59:59Z', 'polygon': '138.133163,9.631553,138.032913,9.417565,138.204918,9.527623,138.133163,9.631553'}

**Comment by jpswinski** [comment]
SlideRule now provides a raster mechanism for very complex polygons and multiple polygons.  Using the `icesat2.toregion` function, the client will create a raster image of the shapefile/geojson/etc and supply that back to the calling application.  If the application passes the raster image as a part of the request to SlideRule, SlideRule will use it for subsetting each granule instead of using the original polygon.

This is useful in a number of cases:
* If your shapefile contains a lot of small regions, using the raster image allows SlideRule to perform a single pass through each granule and only process the areas that are inside the supplied polygons.  Without using the raster image, the client has to submit a separate request for each polygon for each granule.
* If your region of interest is very complex, the polygon-only subsetting logic in SlideRule requires that the convex hull of the region be processed since it cannot handle multiple slices of a ground track.  This means that more data than needed is processed and returned.
* If your polygon(s) have a lot of vertices, the server-side polygon-only subsetting logic can be slow, whereas for the raster logic is a fixed performance hit regardless of the size or complexity of the input.

**Comment by jpswinski** [comment]
Here is an example    
```Python
icesat2.init(url, False)
region = icesat2.toregion(filename)
parms = {
    "poly": region["poly"],
    "raster": region["raster"],
    "srt": icesat2.SRT_LAND,
    "cnf": icesat2.CNF_SURFACE_HIGH,
    "atl08_class": ["atl08_ground"],
    "ats": 10.0,
    "cnt": 10,
    "len": 40.0,
    "res": 20.0,
    "maxi": 6
}
gdf = icesat2.atl06p(parms, asset)
```
