### ISSUE TITLE
Not getting classifications from atl03s

### ISSUE THREAD

**Issue by SmithB** [ICESat2-SlideRule/sliderule-python#47]
When using the ATL03 classification types (rather than the ATL08 classification) icesat2.atl03s returns only info=4.  As I understand it, 'info' should provide the photon classification, which should have values between 0 and 4.

params3={'poly': [{'lat': 39.061078079639884, 'lon': -108.16198432128206},
  {'lat': 39.061078079639884, 'lon': -108.05680058219865},
  {'lat': 38.97935834097313, 'lon': -108.05680058219865},
  {'lat': 38.97935834097313, 'lon': -108.16198432128206},
  {'lat': 39.061078079639884, 'lon': -108.16198432128206}],
 'srt': 3, 'cnf':0}
 D3=icesat2.atl03s(params3, 'ATL03_20201111102237_07370902_004_01.h5',  track=3)

**Comment by jpswinski** [comment]
The reason it is returning 4 (which is UNCLASSIFIED) is because there is no 'atl08_class' specified in the request.  The way the code currently works is that it only performs the ATL08 classification if filtering is requested, otherwise it skips reading the ATL08 data to save time.

This will be changed in the future so that specifying the a special value for 'srt' will force the ATL08 classification.

**Comment by jpswinski** [comment]
In version 1.1.3 the atl03 record has been changed to have `atl08_class` and `atl03_cnf` fields.
