### ISSUE TITLE
ConnectTimeoutError running on mybinder.org

### ISSUE THREAD

**Issue by scottyhq** [ICESat2-SlideRule/sliderule-python#48]
Using the binder link in the repository readme to run sliderule on mybinder.org a user quickly encounters the following error running `icesat2.init("icesat2sliderule.org")`

```pytb
MaxRetryError: HTTPConnectionPool(host='icesat2sliderule.org', port=8500): Max retries exceeded with url: /v1/catalog/service/srds?passing (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f6dbe28e9d0>, 'Connection to icesat2sliderule.org timed out. (connect timeout=10)')) 
```

This seems to be related to egress settings on mybinder.org (only certain ports are allowed), because the code runs fine on other deployments such as the pangeo binder on AWS. The mybinder.org configuration is here: https://github.com/jupyterhub/mybinder.org-deploy/blob/f6dfb4ab34af8cc4419fdf52c7e20c9a8eff0b39/mybinder/values.yaml#L48 

The docs for those settings are here https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/security.html?highlight=networkpolicy#limiting-network-access-from-pods-egress

Is port 8500 an arbitrary choice? Is there a possible workaround to run sliderule from systems that have such egress rules set?
https://github.com/ICESat2-SlideRule/sliderule-python/issues/6

**Comment by jpswinski** [comment]
The infrastructure and code was updated to flow all traffic over port 80.  mybinder.org now works with our example notebooks.

**Comment by jujara** [comment]
Hello,

I am having also an apparent connection error
slide rules start good, I am using condo and I can create an environment and activate it, but
 when I initialise the Icesat2 package:

icesat2.init("icesat2sliderule.org", verbose=True)

Then, I can't connect to server. This is the error:

ERROR:sliderule.sliderule:Connection error to endpoint https://sliderule.icesat2sliderule.org/source/version ...retrying request

ERROR:sliderule.sliderule:Connection error to endpoint https://sliderule.icesat2sliderule.org/source/version ...retrying request

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Julius/sliderule-python/sliderule/icesat2.py", line 402, in init
    sliderule.init(url, verbose, loglevel, organization, desired_nodes, time_to_live, plugins=['icesat2'])
  File "/Users/Julius/sliderule-python/sliderule/sliderule.py", line 547, in init
    check_version(plugins=plugins) # verify compatibility between client and server versions
  File "/Users/Julius/sliderule-python/sliderule/sliderule.py", line 1021, in check_version
    info = get_version()
  File "/Users/Julius/sliderule-python/sliderule/sliderule.py", line 998, in get_version
    rsps = source("version", {})
  File "/Users/Julius/sliderule-python/sliderule/sliderule.py", line 653, in source
    raise FatalError("Unable to complete request due to errors")
sliderule.sliderule.FatalError: Unable to complete request due to errors
>>> 


Best regards

Julius

**Comment by dshean** [comment]
Hi @jujara.  Thanks for asking and providing error messages.  You are pointing to the old endpoint.  You want:
`icesat2.init("slideruleearth.io", verbose=True)`
